2025-10-10 12:45:15,755 - INFO - 127.0.0.1:59238 - GET /api/v1/project/list/projects - Status: [92m200[0m - Time: 1.72s
2025-10-10 12:45:15,806 - INFO - 127.0.0.1:59238 - GET /projects/string/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 12:45:15,817 - INFO - 127.0.0.1:65196 - GET /projects/string/submissions - Status: [93m404[0m - Time: 0.01s - Reason: Not Found
2025-10-10 12:45:15,823 - INFO - 127.0.0.1:55544 - GET /projects/string/metrics - Status: [93m404[0m - Time: 0.01s - Reason: Not Found
2025-10-10 12:45:15,828 - INFO - 127.0.0.1:49898 - GET /projects/string/submissions - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 12:45:27,975 - INFO - 127.0.0.1:56118 - GET /projects/africa/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 12:45:27,981 - INFO - 127.0.0.1:64352 - GET /projects/africa/submissions - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 12:45:32,289 - INFO - 127.0.0.1:64352 - GET /projects/string/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 12:45:32,291 - INFO - 127.0.0.1:56118 - GET /projects/string/submissions - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 12:45:34,223 - INFO - 127.0.0.1:56118 - GET /projects/africa/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 12:45:34,224 - INFO - 127.0.0.1:64352 - GET /projects/africa/submissions - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 13:03:29,427 - INFO - 127.0.0.1:62433 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.00s
2025-10-10 13:03:29,790 - INFO - 127.0.0.1:62433 - GET /api/v1/openapi.json - Status: [92m200[0m - Time: 0.11s
2025-10-10 13:04:15,599 - INFO - 127.0.0.1:60110 - GET /api/v1/submission/all/agent - Status: [91m500[0m - Time: 2.53s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 13:04:22,077 - INFO - 127.0.0.1:50914 - GET /api/v1/submission/all/agent - Status: [91m500[0m - Time: 0.94s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 13:05:05,886 - INFO - 127.0.0.1:56020 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.00s
2025-10-10 13:05:05,991 - INFO - 127.0.0.1:56020 - GET /api/v1/openapi.json - Status: [92m200[0m - Time: 0.00s
2025-10-10 13:05:15,921 - INFO - 127.0.0.1:49667 - GET /api/v1/submission/all/agent - Status: [91m500[0m - Time: 0.57s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 13:05:23,035 - INFO - 127.0.0.1:53274 - GET /api/v1/submission/all/agent - Status: [91m500[0m - Time: 0.63s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 13:05:59,037 - INFO - 127.0.0.1:50379 - GET /api/v1/submission/all/agent - Status: [91m500[0m - Time: 0.58s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 13:06:51,534 - ERROR - HTTPException: Status must be one of: ['assigned', 'accepted', 'rejected', 'redo', 'submitted'] at GET /api/v1/submission/all/agent
2025-10-10 13:06:51,541 - INFO - 127.0.0.1:54557 - GET /api/v1/submission/all/agent - Status: [93m400[0m - Time: 0.01s - Reason: Status must be one of: ['assigned', 'accepted', 'rejected', 'redo', 'submitted']
2025-10-10 13:07:02,412 - INFO - 127.0.0.1:56315 - GET /api/v1/submission/all/agent - Status: [91m500[0m - Time: 0.54s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 13:08:31,306 - INFO - 127.0.0.1:62620 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 7.22s
2025-10-10 13:11:50,965 - INFO - 127.0.0.1:64429 - GET /api/v1/submission/all/agent - Status: [91m500[0m - Time: 0.89s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 13:12:03,376 - INFO - 127.0.0.1:49666 - GET /api/v1/submission/83e7b6ba-3931-48fa-a417-ceec7786e6cc/agent - Status: [92m200[0m - Time: 2.60s
2025-10-10 14:08:12,203 - INFO - 127.0.0.1:54045 - GET /api/v1/status/contributor/ibrahim@example.com - Status: [92m200[0m - Time: 10.14s
2025-10-10 14:08:41,427 - INFO - 127.0.0.1:53632 - GET /api/v1/status/reviewer/ibrahim@example.com - Status: [92m200[0m - Time: 4.37s
2025-10-10 14:09:31,647 - INFO - 127.0.0.1:64092 - GET /api/v1/submission/all/agent - Status: [91m500[0m - Time: 0.65s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 14:10:51,397 - INFO - 127.0.0.1:58969 - GET /api/v1/submission/all/agent - Status: [91m500[0m - Time: 1.12s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 14:23:51,526 - INFO - 127.0.0.1:57288 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.00s
2025-10-10 14:23:51,945 - INFO - 127.0.0.1:57288 - GET /api/v1/openapi.json - Status: [92m200[0m - Time: 0.20s
2025-10-10 14:24:09,337 - INFO - 127.0.0.1:53599 - GET /api/v1/agent/read/all - Status: [92m200[0m - Time: 7.32s
2025-10-10 14:29:35,765 - INFO - 127.0.0.1:57155 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.00s
2025-10-10 14:29:51,068 - INFO - 127.0.0.1:57462 - GET /api/v1/openapi.json - Status: [92m200[0m - Time: 0.31s
2025-10-10 14:30:45,395 - INFO - 127.0.0.1:56198 - GET /api/v1/reviewer/ibrahim@example.com/history - Status: [91m500[0m - Time: 9.51s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 14:35:48,019 - INFO - 127.0.0.1:52459 - GET /api/v1/reviewer/ibrahim@example.com/history - Status: [91m500[0m - Time: 11.03s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 14:36:08,822 - INFO - 127.0.0.1:53358 - GET /api/v1/reviewer/ibrahim@example.com/history - Status: [91m500[0m - Time: 7.13s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 14:40:34,815 - INFO - 127.0.0.1:54459 - GET /api/v1/reviewer/ibrahim@example.com/history - Status: [91m500[0m - Time: 2.90s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 14:41:23,795 - INFO - 127.0.0.1:58956 - GET /api/v1/reviewer/ibrahim@example.com/history - Status: [91m500[0m - Time: 7.09s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 14:46:21,592 - INFO - 127.0.0.1:64210 - GET /api/v1/reviewer/ibrahim@example.com/history - Status: [91m500[0m - Time: 7.36s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 14:46:50,098 - INFO - 127.0.0.1:53313 - GET /api/v1/reviewer/ibrahim@example.com/history - Status: [92m200[0m - Time: 9.92s
2025-10-10 14:48:00,316 - ERROR - HTTPException: Reviewer not found at GET /api/v1/reviewer/83e7b6ba-3931-48fa-a417-ceec7786e6cc/filter
2025-10-10 14:48:00,326 - INFO - 127.0.0.1:57313 - GET /api/v1/reviewer/83e7b6ba-3931-48fa-a417-ceec7786e6cc/filter - Status: [93m404[0m - Time: 1.87s - Reason: Reviewer not found
2025-10-10 14:48:24,129 - INFO - 127.0.0.1:60342 - GET /api/v1/reviewer/ibrahim@example.com/filter - Status: [91m500[0m - Time: 3.53s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 14:51:47,318 - INFO - 127.0.0.1:54209 - GET /api/v1/reviewer/ibrahim@example.com/filter - Status: [92m200[0m - Time: 8.46s
2025-10-10 14:52:14,582 - ERROR - HTTPException: Status must be one of: ['pending', 'accepted', 'rejected', 'redo'] at GET /api/v1/reviewer/ibrahim@example.com/filter
2025-10-10 14:52:14,587 - INFO - 127.0.0.1:60468 - GET /api/v1/reviewer/ibrahim@example.com/filter - Status: [93m400[0m - Time: 1.56s - Reason: Status must be one of: ['pending', 'accepted', 'rejected', 'redo']
2025-10-10 14:52:24,082 - ERROR - HTTPException: Status must be one of: ['pending', 'accepted', 'rejected', 'redo'] at GET /api/v1/reviewer/ibrahim@example.com/filter
2025-10-10 14:52:24,083 - INFO - 127.0.0.1:49296 - GET /api/v1/reviewer/ibrahim@example.com/filter - Status: [93m400[0m - Time: 1.39s - Reason: Status must be one of: ['pending', 'accepted', 'rejected', 'redo']
2025-10-10 14:52:36,845 - ERROR - HTTPException: Status must be one of: ['pending', 'accepted', 'rejected', 'redo'] at GET /api/v1/reviewer/ibrahim@example.com/filter
2025-10-10 14:52:36,846 - INFO - 127.0.0.1:57883 - GET /api/v1/reviewer/ibrahim@example.com/filter - Status: [93m400[0m - Time: 1.36s - Reason: Status must be one of: ['pending', 'accepted', 'rejected', 'redo']
2025-10-10 14:52:54,607 - INFO - 127.0.0.1:51851 - GET /api/v1/reviewer/ibrahim@example.com/filter - Status: [92m200[0m - Time: 3.76s
2025-10-10 14:54:56,660 - ERROR - HTTPException: Reviewer can only set status to accepted, rejected, or redo or pending at PATCH /api/v1/reviewer/update/83e7b6ba-3931-48fa-a417-ceec7786e6cc/review
2025-10-10 14:54:56,663 - INFO - 127.0.0.1:60490 - PATCH /api/v1/reviewer/update/83e7b6ba-3931-48fa-a417-ceec7786e6cc/review - Status: [93m400[0m - Time: 0.01s - Reason: Reviewer can only set status to accepted, rejected, or redo or pending
2025-10-10 14:55:16,986 - INFO - 127.0.0.1:57592 - PATCH /api/v1/reviewer/update/83e7b6ba-3931-48fa-a417-ceec7786e6cc/review - Status: [91m500[0m - Time: 6.43s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 14:57:45,069 - INFO - 127.0.0.1:60163 - PATCH /api/v1/reviewer/update/83e7b6ba-3931-48fa-a417-ceec7786e6cc/review - Status: [91m500[0m - Time: 1.81s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 14:58:09,636 - INFO - 127.0.0.1:58344 - PATCH /api/v1/reviewer/update/83e7b6ba-3931-48fa-a417-ceec7786e6cc/review - Status: [91m500[0m - Time: 6.99s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 14:58:15,937 - INFO - 127.0.0.1:58344 - PATCH /api/v1/reviewer/update/83e7b6ba-3931-48fa-a417-ceec7786e6cc/review - Status: [91m500[0m - Time: 2.20s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 15:06:46,730 - INFO - 127.0.0.1:52269 - PATCH /api/v1/reviewer/update/83e7b6ba-3931-48fa-a417-ceec7786e6cc/review - Status: [91m500[0m - Time: 5.05s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 15:09:23,445 - INFO - 127.0.0.1:57050 - PATCH /api/v1/reviewer/update/83e7b6ba-3931-48fa-a417-ceec7786e6cc/review - Status: [92m200[0m - Time: 7.44s
2025-10-10 15:09:51,030 - INFO - 127.0.0.1:50517 - GET /api/v1/reviewer/ibrahim@example.com/history - Status: [92m200[0m - Time: 5.51s
2025-10-10 15:10:03,900 - INFO - 127.0.0.1:54196 - GET /api/v1/reviewer/ibrahim@example.com/history - Status: [92m200[0m - Time: 2.27s
2025-10-10 15:21:36,645 - INFO - 127.0.0.1:50184 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.00s
2025-10-10 15:21:56,860 - INFO - 127.0.0.1:64264 - GET / - Status: [92m200[0m - Time: 0.00s
2025-10-10 15:22:13,548 - INFO - 127.0.0.1:60953 - GET /favicon.ico - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 15:22:14,248 - INFO - 127.0.0.1:60953 - GET /api/v1/openapi.json - Status: [92m200[0m - Time: 0.44s
2025-10-10 15:22:45,527 - INFO - 127.0.0.1:49672 - GET /api/v1/submission/all/agent - Status: [91m500[0m - Time: 1.05s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 15:23:25,740 - INFO - 127.0.0.1:51666 - GET /api/v1/reviewer/ibrahim@example.com/history - Status: [92m200[0m - Time: 5.36s
2025-10-10 15:55:07,710 - INFO - 127.0.0.1:63937 - PATCH /api/v1/reviewer/update/83e7b6ba-3931-48fa-a417-ceec7786e6cc/review - Status: [92m200[0m - Time: 7.58s
2025-10-10 15:55:20,815 - INFO - 127.0.0.1:59630 - GET /api/v1/reviewer/ibrahim@example.com/history - Status: [92m200[0m - Time: 3.47s
2025-10-10 16:39:48,587 - INFO - 127.0.0.1:53139 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.01s
2025-10-10 16:40:01,832 - INFO - 127.0.0.1:63436 - GET /api/v1/openapi.json - Status: [92m200[0m - Time: 0.18s
2025-10-10 16:41:31,668 - INFO - 127.0.0.1:53241 - GET /api/v1/reviewer/ibrahim@example.com/history - Status: [92m200[0m - Time: 7.60s
2025-10-10 16:42:17,330 - INFO - 127.0.0.1:59897 - PATCH /api/v1/reviewer/update/83e7b6ba-3931-48fa-a417-ceec7786e6cc/review - Status: [92m200[0m - Time: 5.55s
2025-10-10 16:42:23,514 - INFO - 127.0.0.1:59897 - GET /api/v1/reviewer/ibrahim@example.com/history - Status: [92m200[0m - Time: 1.82s
2025-10-10 16:42:51,987 - INFO - 127.0.0.1:52798 - GET /api/v1/submission/83e7b6ba-3931-48fa-a417-ceec7786e6cc/agent - Status: [92m200[0m - Time: 2.40s
2025-10-10 16:43:02,630 - INFO - 127.0.0.1:60098 - GET /api/v1/submission/all/agent - Status: [91m500[0m - Time: 0.55s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 16:46:45,777 - INFO - 127.0.0.1:52819 - GET /api/v1/submission/all/agent - Status: [91m500[0m - Time: 1.49s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-10 16:47:02,077 - INFO - 127.0.0.1:60383 - GET /api/v1/submission/all/agent - Status: [92m200[0m - Time: 5.05s
2025-10-10 17:33:18,925 - INFO - 127.0.0.1:61511 - GET /api/v1/project/list/projects - Status: [92m200[0m - Time: 3.89s
2025-10-10 17:33:19,977 - INFO - 127.0.0.1:61511 - GET /projects/string/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:33:20,009 - INFO - 127.0.0.1:63951 - GET /projects/string/metrics - Status: [93m404[0m - Time: 0.01s - Reason: Not Found
2025-10-10 17:33:20,018 - INFO - 127.0.0.1:56042 - GET /projects/string/submissions - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:33:20,038 - INFO - 127.0.0.1:63951 - GET /projects/string/submissions - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:36:09,696 - INFO - 127.0.0.1:62051 - GET /projects/africa/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:36:09,698 - INFO - 127.0.0.1:53212 - GET /projects/africa/submissions - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:37:42,814 - INFO - 127.0.0.1:60604 - GET /api/v1/project/list/projects - Status: [92m200[0m - Time: 25.21s
2025-10-10 17:37:42,855 - INFO - 127.0.0.1:60604 - GET /projects/string/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:37:42,857 - INFO - 127.0.0.1:49946 - GET /projects/string/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:37:42,859 - INFO - 127.0.0.1:51806 - GET /projects/string/submissions - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:37:42,860 - INFO - 127.0.0.1:57380 - GET /projects/string/submissions - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:38:11,620 - INFO - 127.0.0.1:52946 - GET /projects/africa/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:38:11,626 - INFO - 127.0.0.1:56263 - GET /projects/africa/submissions - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:38:24,870 - INFO - 127.0.0.1:49719 - GET /projects/string/metrics - Status: [93m404[0m - Time: 0.01s - Reason: Not Found
2025-10-10 17:38:24,887 - INFO - 127.0.0.1:51824 - GET /projects/string/submissions - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:38:29,236 - INFO - 127.0.0.1:51824 - GET /projects/africa/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:38:29,237 - INFO - 127.0.0.1:49719 - GET /projects/africa/submissions - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:50:17,968 - INFO - 127.0.0.1:64347 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:51:18,143 - INFO - 127.0.0.1:61226 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:51:19,651 - INFO - 127.0.0.1:61226 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:52:18,111 - INFO - 127.0.0.1:52386 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:52:30,591 - INFO - 127.0.0.1:56878 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:52:34,056 - INFO - 127.0.0.1:56878 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:52:56,018 - INFO - 127.0.0.1:49374 - GET /api/v1/project/list/projects - Status: [92m200[0m - Time: 3.74s
2025-10-10 17:52:56,088 - INFO - 127.0.0.1:49374 - GET /projects/string/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:52:56,091 - INFO - 127.0.0.1:49374 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:52:56,227 - INFO - 127.0.0.1:49374 - GET /projects/string/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:52:56,245 - INFO - 127.0.0.1:49374 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:53:22,902 - INFO - 127.0.0.1:64374 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:53:22,931 - INFO - 127.0.0.1:53485 - GET /projects/africa/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:53:38,183 - INFO - 127.0.0.1:60103 - GET /api/v1/project/list/projects - Status: [92m200[0m - Time: 1.28s
2025-10-10 17:53:38,320 - INFO - 127.0.0.1:60103 - GET /projects/string/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:53:38,324 - INFO - 127.0.0.1:58054 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:53:38,327 - INFO - 127.0.0.1:57722 - GET /projects/string/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:53:38,329 - INFO - 127.0.0.1:58245 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:53:43,217 - INFO - 127.0.0.1:58245 - GET /projects/africa/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:53:43,232 - INFO - 127.0.0.1:57722 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 17:55:01,215 - INFO - 127.0.0.1:51665 - GET /api/v1/submission/all/agent - Status: [92m200[0m - Time: 5.24s
2025-10-10 17:55:36,620 - INFO - 127.0.0.1:64850 - GET /api/v1/submission/all/agent - Status: [92m200[0m - Time: 1.29s
2025-10-10 17:55:49,804 - INFO - 127.0.0.1:63138 - GET /api/v1/submission/all/agent - Status: [92m200[0m - Time: 2.75s
2025-10-10 18:00:18,718 - INFO - 127.0.0.1:50983 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:00:20,809 - INFO - 127.0.0.1:50983 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:00:23,191 - INFO - 127.0.0.1:50983 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:00:27,635 - INFO - 127.0.0.1:50983 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:00:29,173 - INFO - 127.0.0.1:50983 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:00:30,377 - INFO - 127.0.0.1:50983 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:00:34,738 - INFO - 127.0.0.1:50983 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:00:37,166 - INFO - 127.0.0.1:50983 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:00:41,632 - INFO - 127.0.0.1:50983 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:01:05,179 - INFO - 127.0.0.1:60102 - GET /api/v1/project/list/projects - Status: [92m200[0m - Time: 1.96s
2025-10-10 18:01:05,257 - INFO - 127.0.0.1:60102 - GET /projects/string/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:01:05,267 - INFO - 127.0.0.1:60102 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:01:05,271 - INFO - 127.0.0.1:53591 - GET /projects/string/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:01:05,283 - INFO - 127.0.0.1:53591 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:01:13,575 - INFO - 127.0.0.1:58289 - GET /projects/africa/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:01:13,580 - INFO - 127.0.0.1:61230 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:02:04,141 - INFO - 127.0.0.1:57044 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:02:34,307 - INFO - 127.0.0.1:60391 - GET /api/v1/submission/all/agent - Status: [92m200[0m - Time: 2.14s
2025-10-10 18:12:45,125 - INFO - 127.0.0.1:51130 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:12:56,293 - INFO - 127.0.0.1:63311 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:12:56,295 - INFO - 127.0.0.1:61327 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:13:02,722 - INFO - 127.0.0.1:62540 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:13:12,565 - INFO - 127.0.0.1:60562 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:13:32,812 - INFO - 127.0.0.1:59097 - GET /submission/all/agent - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:13:45,795 - INFO - 127.0.0.1:61833 - GET /api/v1//api/project/list/projects - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:13:48,553 - INFO - 127.0.0.1:61833 - GET /api/v1//api/project/list/projects - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:14:07,216 - INFO - 127.0.0.1:50442 - GET /api/v1//api/project/list/projects - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:17:17,837 - INFO - 127.0.0.1:60576 - GET /api/project/list/projects - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:17:22,550 - INFO - 127.0.0.1:60576 - GET /api/project/list/projects - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:17:42,492 - INFO - 127.0.0.1:52811 - GET /api/project/list/projects - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:18:20,251 - INFO - 127.0.0.1:64389 - GET /api/project/list/projects - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:20:25,758 - INFO - 127.0.0.1:55951 - GET /api/project/list/projects - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:23:51,228 - INFO - 127.0.0.1:63897 - GET /api/v1/project/list/projects - Status: [92m200[0m - Time: 3.58s
2025-10-10 18:23:51,347 - INFO - 127.0.0.1:63897 - GET /api/v1/projects/string/metrics - Status: [93m404[0m - Time: 0.01s - Reason: Not Found
2025-10-10 18:23:51,366 - INFO - 127.0.0.1:58584 - GET /api/v1/projects/string/metrics - Status: [93m404[0m - Time: 0.01s - Reason: Not Found
2025-10-10 18:23:54,023 - INFO - 127.0.0.1:57189 - GET /api/v1/submission/all/agent - Status: [92m200[0m - Time: 2.69s
2025-10-10 18:23:55,715 - INFO - 127.0.0.1:53350 - GET /api/v1/submission/all/agent - Status: [92m200[0m - Time: 4.36s
2025-10-10 18:24:03,215 - INFO - 127.0.0.1:49831 - GET /api/v1/projects/africa/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:24:06,863 - INFO - 127.0.0.1:58034 - GET /api/v1/submission/all/agent - Status: [92m200[0m - Time: 3.64s
2025-10-10 18:24:59,988 - INFO - 127.0.0.1:64308 - GET /api/v1/projects/string/metrics - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-10 18:25:01,512 - INFO - 127.0.0.1:58167 - GET /api/v1/submission/all/agent - Status: [92m200[0m - Time: 1.53s
2025-10-10 18:25:04,160 - INFO - 127.0.0.1:58167 - GET /api/v1/projects/africa/metrics - Status: [93m404[0m - Time: 0.01s - Reason: Not Found
2025-10-10 18:25:06,248 - INFO - 127.0.0.1:64308 - GET /api/v1/submission/all/agent - Status: [92m200[0m - Time: 2.09s
2025-10-10 18:26:04,992 - INFO - 127.0.0.1:49837 - GET /api/v1/submission/all/agent - Status: [92m200[0m - Time: 3.89s
2025-10-10 18:28:35,483 - INFO - 127.0.0.1:60985 - GET /api/v1/projects/string/metrics - Status: [93m404[0m - Time: 0.01s - Reason: Not Found
2025-10-10 18:28:36,595 - INFO - 127.0.0.1:50940 - GET /api/v1/submission/all/agent - Status: [92m200[0m - Time: 1.11s
2025-10-10 18:28:40,266 - INFO - 127.0.0.1:50940 - GET /api/v1/projects/africa/metrics - Status: [93m404[0m - Time: 0.01s - Reason: Not Found
2025-10-10 18:28:42,381 - INFO - 127.0.0.1:60985 - GET /api/v1/submission/all/agent - Status: [92m200[0m - Time: 2.12s
2025-10-13 15:51:11,398 - INFO - 127.0.0.1:59764 - GET / - Status: [92m200[0m - Time: 0.00s
2025-10-13 15:51:11,664 - INFO - 127.0.0.1:59764 - GET /favicon.ico - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-13 15:51:15,434 - INFO - 127.0.0.1:59764 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.00s
2025-10-13 15:51:15,656 - INFO - 127.0.0.1:59857 - GET /api/v1/openapi.json - Status: [92m200[0m - Time: 0.07s
2025-10-13 15:59:43,078 - INFO - 127.0.0.1:61318 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.00s
2025-10-13 15:59:43,385 - INFO - 127.0.0.1:61318 - GET /api/v1/openapi.json - Status: [92m200[0m - Time: 0.17s
2025-10-13 16:00:46,756 - INFO - 127.0.0.1:58611 - GET /api/v1/project/project/africa/assigned-users - Status: [92m200[0m - Time: 3.40s
2025-10-13 16:01:11,891 - INFO - 127.0.0.1:51753 - GET /api/v1/project/project/africa/assigned-users - Status: [92m200[0m - Time: 1.47s
2025-10-13 16:01:20,717 - ERROR - HTTPException: Only agent or reviewer roles supported at GET /api/v1/project/project/africa/assigned-users
2025-10-13 16:01:20,722 - INFO - 127.0.0.1:58521 - GET /api/v1/project/project/africa/assigned-users - Status: [93m400[0m - Time: 1.13s - Reason: Only agent or reviewer roles supported
2025-10-13 16:02:09,280 - ERROR - HTTPException: No matching users found at POST /api/v1/project/project/africa/add-users
2025-10-13 16:02:09,282 - INFO - 127.0.0.1:49672 - POST /api/v1/project/project/africa/add-users - Status: [93m404[0m - Time: 1.56s - Reason: No matching users found
2025-10-13 16:02:43,525 - ERROR - HTTPException: No matching users found at POST /api/v1/project/project/africa/add-users
2025-10-13 16:02:43,537 - INFO - 127.0.0.1:60806 - POST /api/v1/project/project/africa/add-users - Status: [93m404[0m - Time: 1.30s - Reason: No matching users found
2025-10-14 07:52:18,490 - INFO - 127.0.0.1:55921 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.00s
2025-10-14 07:52:18,761 - INFO - 127.0.0.1:55921 - GET /api/v1/openapi.json - Status: [92m200[0m - Time: 0.17s
2025-10-14 07:52:38,991 - INFO - 127.0.0.1:60924 - GET /api/v1/project/project/africa/assigned-users - Status: [91m500[0m - Time: 0.98s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-14 08:00:04,321 - INFO - 127.0.0.1:51663 - GET /api/v1/project/project/africa/assigned-users - Status: [91m500[0m - Time: 0.87s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-14 08:00:06,453 - INFO - 127.0.0.1:51663 - GET /api/v1/project/project/africa/assigned-users - Status: [91m500[0m - Time: 0.68s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-14 08:09:41,586 - INFO - 127.0.0.1:50862 - GET /api/v1/project/project/africa/assigned-users - Status: [92m200[0m - Time: 4.42s
2025-10-14 08:10:09,905 - INFO - 127.0.0.1:56030 - GET /api/v1/project/project/africa/assigned-users - Status: [92m200[0m - Time: 2.18s
2025-10-14 08:11:39,290 - INFO - 127.0.0.1:53046 - POST /api/v1/project/projects/africa/reviewers - Status: [92m200[0m - Time: 3.40s
2025-10-14 08:12:07,979 - INFO - 127.0.0.1:61882 - GET /api/v1/project/project/africa/assigned-users - Status: [92m200[0m - Time: 1.54s
2025-10-14 08:15:40,093 - INFO - 127.0.0.1:56770 - GET /api/v1/project/project/africa/assigned-users - Status: [92m200[0m - Time: 6.39s
2025-10-14 08:15:49,616 - INFO - 127.0.0.1:58544 - GET /api/v1/project/project/africa/assigned-users - Status: [92m200[0m - Time: 1.98s
2025-10-14 08:17:45,220 - INFO - 127.0.0.1:51008 - GET /api/v1/project/project/africa/assigned-users - Status: [92m200[0m - Time: 6.27s
2025-10-14 08:18:41,496 - INFO - 127.0.0.1:49870 - GET /api/v1/project/project/africa/assigned-users - Status: [92m200[0m - Time: 13.47s
2025-10-14 08:19:19,168 - INFO - 127.0.0.1:52566 - GET /api/v1/user/all/users - Status: [92m200[0m - Time: 14.16s
2025-10-14 08:22:30,030 - ERROR - HTTPException: No projects found for Role.reviewer with this email at GET /api/v1/project/projects/by-email/lan@example.com
2025-10-14 08:22:30,033 - INFO - 127.0.0.1:63583 - GET /api/v1/project/projects/by-email/lan@example.com - Status: [93m404[0m - Time: 2.29s - Reason: No projects found for Role.reviewer with this email
2025-10-14 08:23:09,797 - INFO - 127.0.0.1:54401 - GET /api/v1/project/projects/by-email/ibrahim@example.com - Status: [92m200[0m - Time: 3.11s
2025-10-14 08:23:20,881 - ERROR - HTTPException: No projects found for Role.reviewer with this email at GET /api/v1/project/projects/by-email/lan@example.com
2025-10-14 08:23:20,884 - INFO - 127.0.0.1:62261 - GET /api/v1/project/projects/by-email/lan@example.com - Status: [93m404[0m - Time: 1.66s - Reason: No projects found for Role.reviewer with this email
2025-10-14 08:28:09,008 - ERROR - HTTPException: No projects found for Role.reviewer with this email at GET /api/v1/project/projects/by-email/lan@example.com
2025-10-14 08:28:09,009 - INFO - 127.0.0.1:53211 - GET /api/v1/project/projects/by-email/lan@example.com - Status: [93m404[0m - Time: 6.70s - Reason: No projects found for Role.reviewer with this email
2025-10-14 08:28:27,670 - INFO - 127.0.0.1:57508 - GET /api/v1/project/projects/by-email/lan@example.com - Status: [92m200[0m - Time: 5.87s
2025-10-14 08:29:13,370 - ERROR - HTTPException: Project not found at GET /api/v1/project/africa/tasks/detailed
2025-10-14 08:29:13,371 - INFO - 127.0.0.1:58140 - GET /api/v1/project/africa/tasks/detailed - Status: [93m404[0m - Time: 2.00s - Reason: Project not found
2025-10-14 08:44:50,728 - INFO - 127.0.0.1:62922 - GET /api/v1/project/africa/tasks/detailed - Status: [92m200[0m - Time: 20.52s
2025-10-14 08:49:06,376 - ERROR - Unhandled error for GET /api/v1/project/africa/tasks/detailed/all
Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 105, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 34 validation errors:
  {'type': 'string_type', 'loc': ('response', 'tasks', 0, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 1, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 2, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 3, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 4, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 5, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 6, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 7, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 8, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 9, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 10, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 11, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 12, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 13, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 14, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 15, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 16, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 17, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 18, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 19, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 20, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 21, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 22, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 23, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 24, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 25, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 26, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 27, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 28, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 29, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 30, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 31, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 32, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 33, 'status'), 'msg': 'Input should be a valid string', 'input': None}

2025-10-14 08:49:06,404 - ERROR - Unhandled exception at GET /api/v1/project/africa/tasks/detailed/all: 34 validation errors:
  {'type': 'string_type', 'loc': ('response', 'tasks', 0, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 1, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 2, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 3, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 4, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 5, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 6, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 7, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 8, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 9, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 10, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 11, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 12, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 13, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 14, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 15, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 16, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 17, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 18, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 19, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 20, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 21, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 22, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 23, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 24, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 25, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 26, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 27, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 28, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 29, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 30, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 31, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 32, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 33, 'status'), 'msg': 'Input should be a valid string', 'input': None}

2025-10-14 08:49:06,412 - ERROR - Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 108, in log_requests
    raise exc
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 105, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 34 validation errors:
  {'type': 'string_type', 'loc': ('response', 'tasks', 0, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 1, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 2, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 3, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 4, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 5, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 6, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 7, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 8, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 9, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 10, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 11, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 12, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 13, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 14, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 15, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 16, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 17, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 18, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 19, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 20, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 21, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 22, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 23, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 24, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 25, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 26, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 27, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 28, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 29, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 30, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 31, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 32, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 33, 'status'), 'msg': 'Input should be a valid string', 'input': None}


2025-10-14 08:53:51,563 - ERROR - Unhandled error for GET /api/v1/project/africa/tasks/detailed/all
Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 105, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 34 validation errors:
  {'type': 'string_type', 'loc': ('response', 'tasks', 0, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 1, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 2, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 3, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 4, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 5, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 6, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 7, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 8, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 9, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 10, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 11, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 12, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 13, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 14, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 15, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 16, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 17, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 18, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 19, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 20, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 21, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 22, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 23, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 24, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 25, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 26, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 27, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 28, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 29, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 30, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 31, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 32, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 33, 'status'), 'msg': 'Input should be a valid string', 'input': None}

2025-10-14 08:53:51,592 - ERROR - Unhandled exception at GET /api/v1/project/africa/tasks/detailed/all: 34 validation errors:
  {'type': 'string_type', 'loc': ('response', 'tasks', 0, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 1, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 2, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 3, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 4, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 5, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 6, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 7, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 8, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 9, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 10, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 11, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 12, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 13, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 14, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 15, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 16, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 17, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 18, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 19, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 20, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 21, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 22, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 23, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 24, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 25, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 26, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 27, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 28, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 29, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 30, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 31, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 32, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 33, 'status'), 'msg': 'Input should be a valid string', 'input': None}

2025-10-14 08:53:51,635 - ERROR - Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 108, in log_requests
    raise exc
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 105, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 34 validation errors:
  {'type': 'string_type', 'loc': ('response', 'tasks', 0, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 1, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 2, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 3, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 4, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 5, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 6, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 7, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 8, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 9, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 10, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 11, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 12, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 13, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 14, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 15, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 16, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 17, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 18, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 19, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 20, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 21, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 22, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 23, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 24, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 25, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 26, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 27, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 28, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 29, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 30, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 31, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 32, 'status'), 'msg': 'Input should be a valid string', 'input': None}
  {'type': 'string_type', 'loc': ('response', 'tasks', 33, 'status'), 'msg': 'Input should be a valid string', 'input': None}


2025-10-14 09:19:59,747 - INFO - 127.0.0.1:60248 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 18.24s
2025-10-14 09:44:28,718 - ERROR - Unhandled error for GET /api/v1/project/africa/tasks/detailed/all
Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 105, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\routers\projects.py", line 835, in list_project_tasks_general
    result = await session.execute(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 463, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2241, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2110, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 1189, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 3273, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 3297, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 1345, in _checkout
    with util.safe_reraise():
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 1342, in _checkout
    fairy._connection_record.get_connection()
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 838, in get_connection
    self.__connect()
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 901, in __connect
    with util.safe_reraise():
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 961, in connect
    await_only(creator_fn(*arg, **kw)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connection.py", line 2421, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 1075, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 1049, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 886, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 931, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 810, in _create_ssl_connection
    do_ssl_upgrade = await pr.on_data
                     ^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\asyncio\selector_events.py", line 1013, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-10-14 09:44:28,867 - ERROR - Unhandled exception at GET /api/v1/project/africa/tasks/detailed/all: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-10-14 09:44:28,878 - ERROR - Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 108, in log_requests
    raise exc
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 105, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\routers\projects.py", line 835, in list_project_tasks_general
    result = await session.execute(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 463, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2241, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2110, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 1189, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 3273, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 3297, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 1345, in _checkout
    with util.safe_reraise():
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 1342, in _checkout
    fairy._connection_record.get_connection()
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 838, in get_connection
    self.__connect()
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 901, in __connect
    with util.safe_reraise():
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 961, in connect
    await_only(creator_fn(*arg, **kw)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connection.py", line 2421, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 1075, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 1049, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 886, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 931, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 810, in _create_ssl_connection
    do_ssl_upgrade = await pr.on_data
                     ^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\asyncio\selector_events.py", line 1013, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

2025-10-14 09:46:21,731 - ERROR - Unhandled error for GET /api/v1/project/africa/tasks/detailed/all
Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connection.py", line 2421, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 1049, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 886, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 931, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 810, in _create_ssl_connection
    do_ssl_upgrade = await pr.on_data
                     ^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 105, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\routers\projects.py", line 835, in list_project_tasks_general
    result = await session.execute(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 463, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2241, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2110, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 1189, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 3273, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 3297, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 718, in checkout
    with util.safe_reraise():
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout
    dbapi_connection = rec.get_connection()
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 838, in get_connection
    self.__connect()
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 901, in __connect
    with util.safe_reraise():
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 961, in connect
    await_only(creator_fn(*arg, **kw)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connection.py", line 2420, in connect
    async with compat.timeout(timeout):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\asyncio\timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
2025-10-14 09:46:21,755 - ERROR - Unhandled exception at GET /api/v1/project/africa/tasks/detailed/all: 
2025-10-14 09:46:21,778 - ERROR - Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connection.py", line 2421, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 1049, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 886, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 931, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 810, in _create_ssl_connection
    do_ssl_upgrade = await pr.on_data
                     ^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 108, in log_requests
    raise exc
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 105, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\routers\projects.py", line 835, in list_project_tasks_general
    result = await session.execute(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 463, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2241, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2110, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 1189, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 3273, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 3297, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 718, in checkout
    with util.safe_reraise():
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout
    dbapi_connection = rec.get_connection()
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 838, in get_connection
    self.__connect()
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 901, in __connect
    with util.safe_reraise():
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 961, in connect
    await_only(creator_fn(*arg, **kw)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connection.py", line 2420, in connect
    async with compat.timeout(timeout):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\asyncio\timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

2025-10-14 09:47:08,201 - ERROR - Unhandled error for GET /api/v1/project/africa/tasks/detailed/all
Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 105, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\routers\projects.py", line 835, in list_project_tasks_general
    result = await session.execute(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 463, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2241, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2110, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 1189, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 3273, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 3297, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 718, in checkout
    with util.safe_reraise():
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout
    dbapi_connection = rec.get_connection()
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 838, in get_connection
    self.__connect()
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 901, in __connect
    with util.safe_reraise():
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 961, in connect
    await_only(creator_fn(*arg, **kw)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connection.py", line 2421, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 1075, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 1049, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 886, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 931, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 810, in _create_ssl_connection
    do_ssl_upgrade = await pr.on_data
                     ^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\asyncio\selector_events.py", line 1013, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-10-14 09:47:08,227 - ERROR - Unhandled exception at GET /api/v1/project/africa/tasks/detailed/all: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-10-14 09:47:08,235 - ERROR - Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 108, in log_requests
    raise exc
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 105, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\routers\projects.py", line 835, in list_project_tasks_general
    result = await session.execute(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 463, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2241, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2110, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 1189, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 3273, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 3297, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 718, in checkout
    with util.safe_reraise():
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout
    dbapi_connection = rec.get_connection()
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 838, in get_connection
    self.__connect()
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 901, in __connect
    with util.safe_reraise():
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 961, in connect
    await_only(creator_fn(*arg, **kw)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connection.py", line 2421, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 1075, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 1049, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 886, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 931, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncpg\connect_utils.py", line 810, in _create_ssl_connection
    do_ssl_upgrade = await pr.on_data
                     ^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\asyncio\selector_events.py", line 1013, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

2025-10-14 09:51:29,592 - INFO - 127.0.0.1:49671 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 12.86s
2025-10-14 09:51:56,241 - INFO - 127.0.0.1:58849 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 4.37s
2025-10-14 10:00:13,522 - INFO - 127.0.0.1:57881 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 10.35s
2025-10-14 10:00:41,354 - INFO - 127.0.0.1:51850 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 6.94s
2025-10-14 10:01:28,727 - INFO - 127.0.0.1:64722 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 4.00s
2025-10-14 10:01:57,328 - INFO - 127.0.0.1:52193 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 4.10s
2025-10-14 10:02:13,276 - INFO - 127.0.0.1:58759 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 5.03s
2025-10-14 10:02:48,119 - INFO - 127.0.0.1:54962 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 4.69s
2025-10-14 10:06:24,327 - INFO - 127.0.0.1:57177 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 9.99s
2025-10-14 10:06:47,823 - INFO - 127.0.0.1:64515 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 5.52s
2025-10-14 10:07:10,841 - INFO - 127.0.0.1:58317 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 6.38s
2025-10-14 10:10:25,638 - INFO - 127.0.0.1:63993 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 4.12s
2025-10-14 10:10:35,483 - INFO - 127.0.0.1:53770 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 4.46s
2025-10-14 10:19:06,832 - INFO - 127.0.0.1:53659 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 16.87s
2025-10-14 10:20:23,323 - ERROR - HTTPException: User not found at GET /api/v1/project/africa/tasks/detailed
2025-10-14 10:20:23,328 - INFO - 127.0.0.1:62436 - GET /api/v1/project/africa/tasks/detailed - Status: [93m404[0m - Time: 3.39s - Reason: User not found
2025-10-14 10:20:44,096 - INFO - 127.0.0.1:50912 - GET /api/v1/project/project/africa/assigned-users - Status: [92m200[0m - Time: 5.71s
2025-10-14 10:23:57,528 - INFO - 127.0.0.1:61325 - GET /api/v1/project/projects/by-email/ibrahim@example.com - Status: [91m500[0m - Time: 4.35s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-14 10:24:29,153 - INFO - 127.0.0.1:52888 - GET /api/v1/project/projects/by-email/ibrahim@example.com - Status: [91m500[0m - Time: 6.00s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-14 10:27:21,336 - INFO - 127.0.0.1:54652 - GET /api/v1/project/projects/by-email/ibrahim@example.com - Status: [91m500[0m - Time: 2.77s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-14 10:27:53,791 - INFO - 127.0.0.1:64115 - GET /api/v1/project/projects/by-email/ibrahim@example.com - Status: [91m500[0m - Time: 8.90s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-14 10:30:57,590 - INFO - 127.0.0.1:52401 - GET /api/v1/project/projects/by-email/ibrahim@example.com - Status: [92m200[0m - Time: 5.76s
2025-10-14 10:31:37,289 - ERROR - HTTPException: User not found at GET /api/v1/project/africa/tasks/detailed
2025-10-14 10:31:37,292 - INFO - 127.0.0.1:59269 - GET /api/v1/project/africa/tasks/detailed - Status: [93m404[0m - Time: 1.45s - Reason: User not found
2025-10-14 10:31:49,723 - INFO - 127.0.0.1:60056 - GET /api/v1/project/africa/tasks/detailed - Status: [92m200[0m - Time: 5.88s
2025-10-14 10:34:09,841 - INFO - 127.0.0.1:51658 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.00s
2025-10-14 10:34:22,750 - INFO - 127.0.0.1:54291 - GET /api/v1/openapi.json - Status: [92m200[0m - Time: 0.55s
2025-10-14 10:36:02,214 - INFO - 127.0.0.1:60698 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 9.55s
2025-10-14 10:38:14,051 - INFO - 127.0.0.1:49698 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 4.21s
2025-10-14 10:42:02,664 - INFO - 127.0.0.1:60893 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 5.66s
2025-10-14 10:42:19,403 - INFO - 127.0.0.1:56238 - GET /api/v1/project/africa/tasks/detailed/all - Status: [92m200[0m - Time: 4.30s
2025-10-14 10:44:25,336 - INFO - 127.0.0.1:50108 - GET /api/v1/project/africa/tasks/detailed - Status: [92m200[0m - Time: 3.91s
2025-10-14 10:45:24,302 - INFO - 127.0.0.1:51981 - GET /api/v1/project/africa/tasks/detailed - Status: [92m200[0m - Time: 3.60s
2025-10-14 10:57:02,344 - ERROR - Unhandled error for POST /api/v1/submission/projects/africa/agent
Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 105, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\routers\submissions.py", line 201, in create_submission
    result_auto_assign =await auto_assign_reviewer(session, project_id, submission)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\utils\reviwer_auto_assignment.py", line 40, in auto_assign_reviewer
    project = project_result.scalars().first()
                           ^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\main.py", line 891, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'Submission' object has no attribute 'exec'
2025-10-14 10:57:02,361 - ERROR - Unhandled exception at POST /api/v1/submission/projects/africa/agent: 'Submission' object has no attribute 'exec'
2025-10-14 10:57:02,368 - ERROR - Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 108, in log_requests
    raise exc
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\middleware.py", line 105, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\routers\submissions.py", line 201, in create_submission
    result_auto_assign =await auto_assign_reviewer(session, project_id, submission)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\Desktop\Lanre\Softmax Tech Solutions\aiogram_backend\src\utils\reviwer_auto_assignment.py", line 40, in auto_assign_reviewer
    project = project_result.scalars().first()
                           ^^^^^^^^^^^^
  File "C:\Users\Olanrewaju Lawal\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\main.py", line 891, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'Submission' object has no attribute 'exec'

2025-10-14 10:57:20,326 - ERROR - HTTPException: Submission already exists for this task at POST /api/v1/submission/projects/africa/agent
2025-10-14 10:57:20,328 - INFO - 127.0.0.1:49734 - POST /api/v1/submission/projects/africa/agent - Status: [93m400[0m - Time: 5.39s - Reason: Submission already exists for this task
2025-10-14 10:58:54,324 - INFO - 127.0.0.1:59250 - GET /api/v1/project/projects/by-email/lan@example.com - Status: [92m200[0m - Time: 4.04s
2025-10-14 10:59:22,202 - INFO - 127.0.0.1:53209 - GET /api/v1/project/africa/tasks/detailed - Status: [92m200[0m - Time: 5.69s
2025-10-14 11:22:55,960 - INFO - 127.0.0.1:60819 - GET /api/v1/project/africa/tasks/detailed - Status: [92m200[0m - Time: 8.84s
2025-10-14 11:23:57,677 - INFO - 127.0.0.1:50271 - POST /api/v1/submission/projects/africa/agent - Status: [92m200[0m - Time: 12.19s
2025-10-14 11:24:43,061 - INFO - 127.0.0.1:63998 - GET /api/v1/project/africa/tasks/detailed - Status: [92m200[0m - Time: 5.30s
2025-10-14 11:31:44,835 - INFO - 127.0.0.1:52632 - GET /api/v1/project/projects/by-email/lan@example.com - Status: [92m200[0m - Time: 5.81s
2025-10-14 13:33:27,999 - INFO - 127.0.0.1:62511 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.03s
2025-10-14 13:33:30,246 - INFO - 127.0.0.1:62511 - GET /api/v1/openapi.json - Status: [92m200[0m - Time: 0.49s
2025-10-14 13:34:17,269 - INFO - 127.0.0.1:50959 - GET /api/v1/telegram/login - Status: [92m200[0m - Time: 6.82s
2025-10-15 04:39:10,300 - INFO - 127.0.0.1:56393 - GET / - Status: [92m200[0m - Time: 0.00s
2025-10-15 04:39:10,416 - INFO - 127.0.0.1:56393 - GET /favicon.ico - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-15 04:39:15,153 - INFO - 127.0.0.1:64332 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.00s
2025-10-15 04:39:25,635 - INFO - 127.0.0.1:65283 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.00s
2025-10-15 04:39:26,011 - INFO - 127.0.0.1:65283 - GET /api/v1/openapi.json - Status: [92m200[0m - Time: 0.17s
2025-10-15 04:40:41,623 - INFO - 127.0.0.1:59274 - GET /api/v1/project/africa/tasks/detailed - Status: [92m200[0m - Time: 8.30s
2025-10-15 04:41:00,570 - INFO - 127.0.0.1:63504 - GET /api/v1/project/africa/tasks/detailed - Status: [92m200[0m - Time: 3.36s
2025-10-15 04:42:19,279 - INFO - 127.0.0.1:64150 - POST /api/v1/submission/projects/africa/agent - Status: [92m200[0m - Time: 10.13s
2025-10-15 04:43:35,528 - INFO - 127.0.0.1:55251 - POST /api/v1/submission/projects/africa/agent - Status: [92m200[0m - Time: 7.21s
2025-10-15 04:44:28,537 - INFO - 127.0.0.1:54303 - GET /api/v1/project/africa/tasks/detailed - Status: [92m200[0m - Time: 4.41s
2025-10-15 04:46:23,049 - INFO - 127.0.0.1:63187 - POST /api/v1/project/projects/africa/reviewers - Status: [92m200[0m - Time: 3.50s
2025-10-15 04:46:45,830 - INFO - 127.0.0.1:58862 - GET /api/v1/project/project/africa/assigned-users - Status: [92m200[0m - Time: 2.19s
2025-10-15 04:47:09,254 - INFO - 127.0.0.1:53378 - GET /api/v1/project/project/africa/assigned-users - Status: [92m200[0m - Time: 1.77s
2025-10-15 04:47:47,455 - INFO - 127.0.0.1:55038 - POST /api/v1/reviewer/assign_submission_to_reviewer/ - Status: [91m500[0m - Time: 1.81s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-15 04:51:07,205 - INFO - 127.0.0.1:63322 - POST /api/v1/reviewer/assign_submission_to_reviewer/ - Status: [91m500[0m - Time: 1.55s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-15 04:51:27,878 - INFO - 127.0.0.1:51307 - POST /api/v1/reviewer/assign_submission_to_reviewer/ - Status: [92m200[0m - Time: 7.11s
2025-10-15 04:52:32,940 - INFO - 127.0.0.1:58384 - GET /api/v1/project/africa/tasks/detailed - Status: [92m200[0m - Time: 5.67s
2025-10-15 05:03:44,981 - ERROR - HTTPException: This submission is already assigned to the reviewer and not rejected at POST /api/v1/reviewer/assign_submission_to_reviewer/
2025-10-15 05:03:44,991 - INFO - 127.0.0.1:56964 - POST /api/v1/reviewer/assign_submission_to_reviewer/ - Status: [93m400[0m - Time: 5.39s - Reason: This submission is already assigned to the reviewer and not rejected
2025-10-15 05:04:06,073 - ERROR - HTTPException: This submission 8b8649b9-05c9-4745-8776-a949abd3438f is already assigned to the reviewer lan@example.com and not rejected at POST /api/v1/reviewer/assign_submission_to_reviewer/
2025-10-15 05:04:06,075 - INFO - 127.0.0.1:55067 - POST /api/v1/reviewer/assign_submission_to_reviewer/ - Status: [93m400[0m - Time: 6.28s - Reason: This submission 8b8649b9-05c9-4745-8776-a949abd3438f is already assigned to the reviewer lan@example.com and not rejected
2025-10-15 05:04:21,790 - ERROR - HTTPException: This submission 8b8649b9-05c9-4745-8776-a949abd3438f is already assigned to the reviewer lan@example.com and not rejected at POST /api/v1/reviewer/assign_submission_to_reviewer/
2025-10-15 05:04:21,791 - INFO - 127.0.0.1:52495 - POST /api/v1/reviewer/assign_submission_to_reviewer/ - Status: [93m400[0m - Time: 2.33s - Reason: This submission 8b8649b9-05c9-4745-8776-a949abd3438f is already assigned to the reviewer lan@example.com and not rejected
2025-10-15 05:11:01,063 - INFO - 127.0.0.1:60677 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.00s
2025-10-15 05:11:01,403 - INFO - 127.0.0.1:60677 - GET /api/v1/openapi.json - Status: [92m200[0m - Time: 0.15s
2025-10-15 05:11:14,114 - INFO - 127.0.0.1:62538 - GET /api/v1/project/list/projects - Status: [92m200[0m - Time: 1.98s
2025-10-15 05:11:56,232 - INFO - 127.0.0.1:54226 - POST /api/v1/project/get/project - Status: [92m200[0m - Time: 2.11s
2025-10-15 05:13:45,107 - INFO - 127.0.0.1:53414 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.00s
2025-10-15 05:13:57,025 - INFO - 127.0.0.1:57100 - GET /api/v1/openapi.json - Status: [92m200[0m - Time: 0.07s
2025-10-15 05:14:43,765 - INFO - 127.0.0.1:55626 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.00s
2025-10-15 05:14:55,080 - INFO - 127.0.0.1:54194 - GET /api/v1/openapi.json - Status: [92m200[0m - Time: 0.05s
2025-10-15 05:15:32,997 - INFO - 127.0.0.1:57221 - PATCH /api/v1/project/update/project/africa - Status: [92m200[0m - Time: 3.97s
2025-10-16 10:28:54,988 - INFO - 127.0.0.1:51290 - GET / - Status: [92m200[0m - Time: 0.00s
2025-10-16 10:28:55,217 - INFO - 127.0.0.1:51290 - GET /favicon.ico - Status: [93m404[0m - Time: 0.00s - Reason: Not Found
2025-10-16 10:29:00,903 - INFO - 127.0.0.1:53646 - GET /api/v1/docs - Status: [92m200[0m - Time: 0.00s
2025-10-16 10:29:02,753 - INFO - 127.0.0.1:60186 - GET /api/v1/openapi.json - Status: [92m200[0m - Time: 0.23s
2025-10-16 10:29:16,401 - INFO - 127.0.0.1:56542 - GET /api/v1/project/list/projects - Status: [92m200[0m - Time: 2.33s
2025-10-16 10:29:47,568 - ERROR - HTTPException: Project name already exists at POST /api/v1/project/create/project
2025-10-16 10:29:47,572 - INFO - 127.0.0.1:50790 - POST /api/v1/project/create/project - Status: [93m400[0m - Time: 1.69s - Reason: Project name already exists
2025-10-16 10:30:04,974 - ERROR - HTTPException: Project name already exists at POST /api/v1/project/create/project
2025-10-16 10:30:04,979 - INFO - 127.0.0.1:58654 - POST /api/v1/project/create/project - Status: [93m400[0m - Time: 1.41s - Reason: Project name already exists
2025-10-16 10:30:21,977 - INFO - 127.0.0.1:58722 - POST /api/v1/project/create/project - Status: [92m200[0m - Time: 3.73s
2025-10-16 10:31:22,725 - INFO - 127.0.0.1:49667 - POST /api/v1/user/create - Status: [91m500[0m - Time: 4.74s - Reason: {'message': 'Database error occurred', 'resolution': 'Please try again later', 'error_code': 'database_error'}
2025-10-16 10:32:29,972 - INFO - 127.0.0.1:65097 - POST /api/v1/user/create - Status: [92m200[0m - Time: 4.22s
2025-10-16 10:33:09,192 - INFO - 127.0.0.1:63552 - POST /api/v1/user/create - Status: [92m200[0m - Time: 4.45s
